### ISSUE TITLE
Dataset duplicated

### ISSUE THREAD

**Issue by Bontempogianpaolo1** [federicacitarrella/FusionFlow#29]
As you can see from the picture below each job contains a huge quantity of data. The reason is the presence of duplicates inside.

**Comment by Bontempogianpaolo1** [comment]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/28188499/149429170-2e1df272-a019-44cb-a99b-88203392d8a7.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/28188499/149429205-f8991610-979a-4a93-bb2a-442d64a5fb0b.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/28188499/149429400-466a2917-6aaf-4c44-a8d5-7f956e667ae1.png">

**Comment by federicacitarrella** [comment]
The EricScript database size is 8.3 GB. It is saved in the work directory, which is just a temporary directory that saves all the files used in the pipeline once (in this case it contains the EricScript database and other smaller files needed for the execution). The EricScript database is also copied in the results directory to be directly used in subsequently pipeline execution. The work directory can be deleted after the pipeline execution, while the results directory contains all the output files and all the databases and files needed to execute again the pipeline skipping the downloader processes, so it can be deleted but, in this case, a new pipeline execution will run again the downloader processes. 
Why do you think there are duplicates?

**Comment by Bontempogianpaolo1** [comment]
You are right. The work directory can be deleted after the pipeline execution but a normal user wouldn't do that. 

A normal user could also remove the result folder and not the work folder. In this way, the same dataset will be stored N times inside the work folder. With this pull request #36, I think we can resolve easily this problem, simplifying the initial code too
